//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class ScoreKeep
	{
		double totalDecayed, decayedDestroyed, whiteDestroyed, negWhiteAffect;


		public ScoreKeep (double totalDecayed)
		{
			this.decayedDestroyed = 0;
			this.whiteDestroyed = 0;
			this.totalDecayed = totalDecayed;
			this.negWhiteAffect = .5; //very subject to change
		}
	
		//calculates destroyedDecay/totalDecay		
		public double decayGrade(){
			return (decayedDestroyed / totalDecayed);
		}
		public double overAll(){
			return (decayGrade - negWhiteAffect * whiteDestroyed);
		}

		public void incDecayDestroy(){
			this.decayedDestroyed++;
		}

		public void incWhiteDestroy(){
			this.whiteDestroyed++;
		}
}
}

